### PR TITLE
Conserve vertical space

### PR DESCRIPTION
**Pull request by bsobhani**
Makes the 3x2 grid 2x3, and puts the since and until date selections on the same row.

### CODE REVIEW

**Comment by danielballan** [comment]
Before (`master` branch):

image

After (this PR branch):

image

This looks like a good improvement to me.

Referencing the suggestion in #78:

> I wonder if the date might use "Date range: 'entry since' - 'entry until'"

I think @cryos had in mind

```
Date range: [since input] – [until input]
```

with an [en dash](https://en.wikipedia.org/wiki/Dash#En_dash) in between. This PR currently has it like:

```
Since: [since input] Until: [until input]
```

I think the original suggestion might be a little better, a little easier to for users to quickly grasp without thinking.

**Comment by danielballan** [comment]
While we are here, should we change the label "24h" to "24 Hours"? I have internalized that abbreviation can be a barrier to non-native English speakers, and it seems we have plenty of space to spell it out here. It would also make it consistent with the other labels.

**Comment by bsobhani** [comment]
I have no strong opinion either way but I made the changes so we can look at them:

date_range

**Comment by danielballan** [comment]
That screenshot looks a bit cramped to my eye, but it's being shown in a very narrow window in that example. If I make the window just a bit wider so that there is no horizontal scrollbar anymore, the top area looks more reasonably spaced out.

image

I consulted @cryos briefly via Teams, and we are both happy to merge this as forward progress. Thanks, @bsobhani.

**Comment by danielballan** [comment]
Confirmed locally that `flake8` and `pytest` pass, since Travis-CI is broken. (Needs migration to GH Actions.)

**Pull request merged**
